
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


public class LoginFrame extends javax.swing.JFrame {

      /**
       * Creates new form LoginFrame
       */
      public LoginFrame() {
            initComponents();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            nothPnl = new javax.swing.JPanel();
            jLabel3 = new javax.swing.JLabel();
            southPnl = new javax.swing.JPanel();
            loginBtn = new javax.swing.JButton();
            regBtn = new javax.swing.JButton();
            cancelBtn = new javax.swing.JButton();
            westPnl = new javax.swing.JPanel();
            eastPnl = new javax.swing.JPanel();
            centerPnl = new javax.swing.JPanel();
            jPanel2 = new javax.swing.JPanel();
            jPanel4 = new javax.swing.JPanel();
            jPanel8 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jPanel6 = new javax.swing.JPanel();
            usernameTf = new javax.swing.JTextField();
            jPanel5 = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            jPanel7 = new javax.swing.JPanel();
            passwordTf = new javax.swing.JPasswordField();
            jPanel3 = new javax.swing.JPanel();
            jPanel9 = new javax.swing.JPanel();
            statusLbl = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Könyvtárkezelő szimulátor - belépés");
            setBackground(new java.awt.Color(204, 255, 255));
            getContentPane().setLayout(new java.awt.GridLayout(1, 1));

            jPanel1.setBackground(new java.awt.Color(204, 255, 255));
            jPanel1.setLayout(new java.awt.BorderLayout());

            nothPnl.setBackground(new java.awt.Color(204, 255, 255));
            nothPnl.setMinimumSize(new java.awt.Dimension(400, 45));
            nothPnl.setPreferredSize(new java.awt.Dimension(400, 45));

            jLabel3.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel3.setText("Bejelentkezés/Regisztráció");
            jLabel3.setPreferredSize(new java.awt.Dimension(250, 35));
            nothPnl.add(jLabel3);

            jPanel1.add(nothPnl, java.awt.BorderLayout.NORTH);

            southPnl.setBackground(new java.awt.Color(204, 255, 255));
            southPnl.setPreferredSize(new java.awt.Dimension(400, 45));
            southPnl.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

            loginBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
            loginBtn.setText("Bejelentkezés");
            loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            loginBtn.setPreferredSize(new java.awt.Dimension(130, 30));
            southPnl.add(loginBtn);

            regBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
            regBtn.setText("Regisztráció");
            regBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            regBtn.setPreferredSize(new java.awt.Dimension(130, 30));
            southPnl.add(regBtn);

            cancelBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
            cancelBtn.setText("Mégsem");
            cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            cancelBtn.setPreferredSize(new java.awt.Dimension(125, 30));
            southPnl.add(cancelBtn);

            jPanel1.add(southPnl, java.awt.BorderLayout.SOUTH);

            westPnl.setBackground(new java.awt.Color(204, 255, 255));
            westPnl.setPreferredSize(new java.awt.Dimension(20, 210));

            javax.swing.GroupLayout westPnlLayout = new javax.swing.GroupLayout(westPnl);
            westPnl.setLayout(westPnlLayout);
            westPnlLayout.setHorizontalGroup(
                  westPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 20, Short.MAX_VALUE)
            );
            westPnlLayout.setVerticalGroup(
                  westPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 210, Short.MAX_VALUE)
            );

            jPanel1.add(westPnl, java.awt.BorderLayout.WEST);

            eastPnl.setBackground(new java.awt.Color(204, 255, 255));
            eastPnl.setPreferredSize(new java.awt.Dimension(70, 210));

            javax.swing.GroupLayout eastPnlLayout = new javax.swing.GroupLayout(eastPnl);
            eastPnl.setLayout(eastPnlLayout);
            eastPnlLayout.setHorizontalGroup(
                  eastPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 70, Short.MAX_VALUE)
            );
            eastPnlLayout.setVerticalGroup(
                  eastPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 210, Short.MAX_VALUE)
            );

            jPanel1.add(eastPnl, java.awt.BorderLayout.EAST);

            centerPnl.setLayout(new java.awt.GridLayout(4, 2));

            jPanel2.setBackground(new java.awt.Color(204, 255, 255));
            jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
            centerPnl.add(jPanel2);

            jPanel4.setBackground(new java.awt.Color(204, 255, 255));

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                  jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 155, Short.MAX_VALUE)
            );
            jPanel4Layout.setVerticalGroup(
                  jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 52, Short.MAX_VALUE)
            );

            centerPnl.add(jPanel4);

            jPanel8.setBackground(new java.awt.Color(204, 255, 255));
            jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

            jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
            jLabel1.setText("Felhasználónév:");
            jLabel1.setPreferredSize(new java.awt.Dimension(110, 30));
            jPanel8.add(jLabel1);

            centerPnl.add(jPanel8);

            jPanel6.setBackground(new java.awt.Color(204, 255, 255));
            jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

            usernameTf.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
            usernameTf.setPreferredSize(new java.awt.Dimension(150, 30));
            jPanel6.add(usernameTf);

            centerPnl.add(jPanel6);

            jPanel5.setBackground(new java.awt.Color(204, 255, 255));
            jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

            jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
            jLabel2.setText("Jelszó:");
            jLabel2.setPreferredSize(new java.awt.Dimension(110, 30));
            jPanel5.add(jLabel2);

            centerPnl.add(jPanel5);

            jPanel7.setBackground(new java.awt.Color(204, 255, 255));
            jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

            passwordTf.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
            passwordTf.setPreferredSize(new java.awt.Dimension(150, 30));
            jPanel7.add(passwordTf);

            centerPnl.add(jPanel7);

            jPanel3.setBackground(new java.awt.Color(204, 255, 255));

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                  jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 155, Short.MAX_VALUE)
            );
            jPanel3Layout.setVerticalGroup(
                  jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 52, Short.MAX_VALUE)
            );

            centerPnl.add(jPanel3);

            jPanel9.setBackground(new java.awt.Color(204, 255, 255));
            jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

            statusLbl.setForeground(java.awt.Color.red);
            statusLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            statusLbl.setPreferredSize(new java.awt.Dimension(150, 30));
            jPanel9.add(statusLbl);

            centerPnl.add(jPanel9);

            jPanel1.add(centerPnl, java.awt.BorderLayout.CENTER);

            getContentPane().add(jPanel1);

            pack();
      }// </editor-fold>//GEN-END:initComponents

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new LoginFrame().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton cancelBtn;
      private javax.swing.JPanel centerPnl;
      private javax.swing.JPanel eastPnl;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanel2;
      private javax.swing.JPanel jPanel3;
      private javax.swing.JPanel jPanel4;
      private javax.swing.JPanel jPanel5;
      private javax.swing.JPanel jPanel6;
      private javax.swing.JPanel jPanel7;
      private javax.swing.JPanel jPanel8;
      private javax.swing.JPanel jPanel9;
      private javax.swing.JButton loginBtn;
      private javax.swing.JPanel nothPnl;
      private javax.swing.JPasswordField passwordTf;
      private javax.swing.JButton regBtn;
      private javax.swing.JPanel southPnl;
      private javax.swing.JLabel statusLbl;
      private javax.swing.JTextField usernameTf;
      private javax.swing.JPanel westPnl;
      // End of variables declaration//GEN-END:variables

      public JButton getloginBtn (){
            return loginBtn;
      }

      public JButton getRegBtn (){
            return regBtn;
      }
      
      public JButton  getcancelBtn (){
            return cancelBtn;
      }

      public JTextField getusernameTf(){
            return usernameTf;
      }
      
      public void setusernameTf(String text){
            usernameTf.setText(text);
      }

      public JPasswordField getpasswordTf(){
            return passwordTf;
      }
      
      public void setpasswordTf(String text){
            passwordTf.setText(text); 
      }

      public JLabel getstatusLbl(){
            return statusLbl;
      }
      
      public void setstatusLbl(String text){
            statusLbl.setText(text);
      }


}
