
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JPasswordField;
import javax.swing.JTable;


public class MainFrame extends javax.swing.JFrame {


      public MainFrame() {
            initComponents();
            fillComboBook();
            fillComboMember();
      }


      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        modMemberBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        newMemberBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        phoneTf = new javax.swing.JTextField();
        emailTf = new javax.swing.JTextField();
        cancelMemberBtn = new javax.swing.JButton();
        statusLbl = new javax.swing.JLabel();
        userLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        userTextLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        authorTf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        titleTf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        quantityTf = new javax.swing.JTextField();
        newBookBtn = new javax.swing.JButton();
        modBookBtn = new javax.swing.JButton();
        cancelBookBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        trDirTf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        bidTf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        midTf = new javax.swing.JTextField();
        newTrBtn = new javax.swing.JButton();
        cancelTrBtn = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        ComboBook = new javax.swing.JComboBox<>();
        ComboMember = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblMember = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblBook = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblTran = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDebit = new javax.swing.JTable();
        exitBtn = new javax.swing.JButton();
        BalanceLbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        userTextLbl1 = new javax.swing.JLabel();
        pfPIN = new javax.swing.JPasswordField();
        btnPIN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Könyvtárkezelő szimulátor");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1060, 700));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        modMemberBtn.setBackground(new java.awt.Color(204, 255, 204));
        modMemberBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        modMemberBtn.setForeground(new java.awt.Color(102, 153, 0));
        modMemberBtn.setText("Módosít");
        modMemberBtn.setToolTipText("A kiválaszott tag adatait átírhatjuk majd frissítjük ezzel a gombbal.");
        modMemberBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modMemberBtn.setEnabled(false);
        modMemberBtn.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 0));
        jLabel1.setText("Tagok");

        newMemberBtn.setBackground(new java.awt.Color(204, 255, 204));
        newMemberBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        newMemberBtn.setForeground(new java.awt.Color(102, 153, 0));
        newMemberBtn.setText("Új");
        newMemberBtn.setToolTipText("Ha nincs kiválasztva \"Tag kód\" (azaz 0), akkor a többi Tagok mező kitöltésével új tagot vehetünk fel.\n Ha a \"Tag kód\"-ban kiválasztunk egy meglévő tagot, akkor ez a gomb inaktív.");
        newMemberBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newMemberBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        newMemberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMemberBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Név:");
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Telefon:");
        jLabel3.setMaximumSize(new java.awt.Dimension(60, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("E-mail:");
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Tag kód:");
        jLabel5.setMaximumSize(new java.awt.Dimension(60, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Könyvek");

        nameTf.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        nameTf.setForeground(new java.awt.Color(102, 153, 0));

        phoneTf.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        phoneTf.setForeground(new java.awt.Color(102, 153, 0));

        emailTf.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        emailTf.setForeground(new java.awt.Color(102, 153, 0));

        cancelMemberBtn.setBackground(new java.awt.Color(204, 255, 204));
        cancelMemberBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        cancelMemberBtn.setForeground(new java.awt.Color(102, 153, 0));
        cancelMemberBtn.setText("Mégse");
        cancelMemberBtn.setToolTipText("Törli az összes beviteli mezőt.");
        cancelMemberBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelMemberBtn.setPreferredSize(new java.awt.Dimension(90, 30));

        statusLbl.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        statusLbl.setForeground(new java.awt.Color(204, 0, 204));
        statusLbl.setText("Nincs közlemény");

        userLbl.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        userLbl.setForeground(new java.awt.Color(204, 0, 204));
        userLbl.setText("jLabel7");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        userTextLbl.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        userTextLbl.setForeground(new java.awt.Color(204, 0, 204));
        userTextLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userTextLbl.setText("Könyvtáros:");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Könyv kód:");
        jLabel7.setMaximumSize(new java.awt.Dimension(60, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(60, 20));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Szerző:");
        jLabel8.setPreferredSize(new java.awt.Dimension(60, 20));

        authorTf.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        authorTf.setForeground(new java.awt.Color(102, 102, 255));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Cím:");
        jLabel9.setMaximumSize(new java.awt.Dimension(60, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(60, 20));

        titleTf.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titleTf.setForeground(new java.awt.Color(102, 102, 255));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Készlet:");
        jLabel10.setPreferredSize(new java.awt.Dimension(60, 20));

        quantityTf.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        quantityTf.setForeground(new java.awt.Color(102, 102, 255));

        newBookBtn.setBackground(new java.awt.Color(153, 204, 255));
        newBookBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        newBookBtn.setForeground(new java.awt.Color(102, 102, 255));
        newBookBtn.setText("Új");
        newBookBtn.setToolTipText("Ha nincs kiválasztva \"Könyv kód\" (azaz 0), akkor a többi Könyvek mező kitöltésével új könyvet vehetünk fel.\n Ha a \"Könyv kód\"-ban kiválasztunk egy meglévő könyvet, akkor ez a gomb inaktív.");
        newBookBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newBookBtn.setPreferredSize(new java.awt.Dimension(90, 30));

        modBookBtn.setBackground(new java.awt.Color(153, 204, 255));
        modBookBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        modBookBtn.setForeground(new java.awt.Color(102, 102, 255));
        modBookBtn.setText("Módosít");
        modBookBtn.setToolTipText("A kiválaszott könyv adatait átírhatjuk majd frissítjük ezzel a gombbal.");
        modBookBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modBookBtn.setEnabled(false);
        modBookBtn.setPreferredSize(new java.awt.Dimension(90, 30));

        cancelBookBtn.setBackground(new java.awt.Color(153, 204, 255));
        cancelBookBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        cancelBookBtn.setForeground(new java.awt.Color(102, 102, 255));
        cancelBookBtn.setText("Mégse");
        cancelBookBtn.setToolTipText("Törli az összes beviteli mezőt.");
        cancelBookBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBookBtn.setPreferredSize(new java.awt.Dimension(90, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 153, 0));
        jLabel11.setText("Tranzakciók");

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 153, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Kölcsönzés(-1)  ||  Visszavétel(1)");
        jLabel13.setPreferredSize(new java.awt.Dimension(60, 20));

        trDirTf.setEditable(false);
        trDirTf.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        trDirTf.setForeground(new java.awt.Color(204, 153, 0));
        trDirTf.setText("-1");

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 153, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Könyv kód:");
        jLabel14.setMaximumSize(new java.awt.Dimension(60, 20));
        jLabel14.setPreferredSize(new java.awt.Dimension(60, 20));

        bidTf.setEditable(false);
        bidTf.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        bidTf.setForeground(new java.awt.Color(204, 153, 0));

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 153, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Tag kód:");
        jLabel15.setPreferredSize(new java.awt.Dimension(60, 20));

        midTf.setEditable(false);
        midTf.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        midTf.setForeground(new java.awt.Color(204, 153, 0));

        newTrBtn.setBackground(new java.awt.Color(255, 255, 204));
        newTrBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        newTrBtn.setForeground(new java.awt.Color(204, 153, 0));
        newTrBtn.setText("Új");
        newTrBtn.setToolTipText("A Tagok és a Könyvek részben kell választani egy-egy azonosítót, ami a fenti mezőkbe automatikusan beíródik. Irányt választani kell. A gombbal rögzítjük a tranzakciót. A gomb csak akkor aktív, ha a \"Könyv kód\" és a \"Tag kód\" is ki van töltve.");
        newTrBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newTrBtn.setEnabled(false);
        newTrBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        newTrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTrBtnActionPerformed(evt);
            }
        });

        cancelTrBtn.setBackground(new java.awt.Color(255, 255, 204));
        cancelTrBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        cancelTrBtn.setForeground(new java.awt.Color(204, 153, 0));
        cancelTrBtn.setText("Mégse");
        cancelTrBtn.setToolTipText("Törli az összes beviteli mezőt.");
        cancelTrBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelTrBtn.setPreferredSize(new java.awt.Dimension(90, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(204, 153, 0));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("ki");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(204, 153, 0));
        jRadioButton2.setText("be");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("System info:");

        ComboBook.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ComboBook.setForeground(new java.awt.Color(102, 102, 255));
        ComboBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        ComboBook.setMinimumSize(new java.awt.Dimension(31, 13));
        ComboBook.setPreferredSize(new java.awt.Dimension(31, 13));
        ComboBook.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBookPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        ComboBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBookActionPerformed(evt);
            }
        });

        ComboMember.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ComboMember.setForeground(new java.awt.Color(102, 153, 0));
        ComboMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        ComboMember.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ComboMemberPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        ComboMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMemberActionPerformed(evt);
            }
        });
        ComboMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ComboMemberKeyReleased(evt);
            }
        });

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(600, 400));

        TblMember.setBackground(new java.awt.Color(204, 255, 204));
        TblMember.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        TblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        TblMember.setEnabled(false);
        jScrollPane1.setViewportView(TblMember);

        jTabbedPane1.addTab("Tagok", jScrollPane1);

        TblBook.setBackground(new java.awt.Color(153, 204, 255));
        TblBook.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        TblBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblBook.setEnabled(false);
        jScrollPane2.setViewportView(TblBook);

        jTabbedPane1.addTab("Könyvek", jScrollPane2);

        TblTran.setBackground(new java.awt.Color(255, 255, 204));
        TblTran.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        TblTran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblTran.setEnabled(false);
        jScrollPane3.setViewportView(TblTran);

        jTabbedPane1.addTab("Tranzakciók", jScrollPane3);

        tblDebit.setBackground(new java.awt.Color(255, 102, 102));
        tblDebit.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        tblDebit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDebit.setEnabled(false);
        jScrollPane4.setViewportView(tblDebit);

        jTabbedPane1.addTab("Tartozás", jScrollPane4);

        exitBtn.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 51, 0));
        exitBtn.setText("Kilépés");
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BalanceLbl.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BalanceLbl.setForeground(new java.awt.Color(102, 153, 0));
        BalanceLbl.setText("0");

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 153, 0));
        jLabel12.setText("Tartozás:");

        userTextLbl1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        userTextLbl1.setForeground(new java.awt.Color(204, 0, 204));
        userTextLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userTextLbl1.setText("Új PIN kód:");

        pfPIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pfPINKeyReleased(evt);
            }
        });

        btnPIN.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnPIN.setForeground(new java.awt.Color(204, 0, 204));
        btnPIN.setText("PIN csere");
        btnPIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPIN.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(newMemberBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modMemberBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cancelMemberBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nameTf, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(phoneTf, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(emailTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(ComboMember, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BalanceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(authorTf, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(titleTf, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(quantityTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ComboBook, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(newBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cancelBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(userTextLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(userLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(userTextLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnPIN, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                            .addComponent(pfPIN))
                                        .addGap(69, 69, 69))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(newTrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cancelTrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14))
                                    .addComponent(bidTf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(midTf, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(trDirTf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trDirTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bidTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(midTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newTrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelTrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComboMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(BalanceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phoneTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newMemberBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(modMemberBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelMemberBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ComboBook, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(authorTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(titleTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(quantityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(modBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(jSeparator1)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userTextLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userTextLbl1)
                            .addComponent(pfPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPIN)
                        .addContainerGap(28, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

      private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
            // TODO add your handling code here:
            trDirTf.setText("-1");
      }//GEN-LAST:event_jRadioButton1ActionPerformed

      private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
            // TODO add your handling code here:
            trDirTf.setText("1");
      }//GEN-LAST:event_jRadioButton2ActionPerformed

      private void ComboBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBookActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_ComboBookActionPerformed

      private void ComboBookPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBookPopupMenuWillBecomeInvisible
            // TODO add your handling code here:
            String tmp = ComboBook.getSelectedItem().toString();
            String sql = "select * from books where bookid = ?";
            try {
                  PreparedStatement pstmt = null;
                  ResultSet rs = null;
                  Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/library?user=root&password=");
                  pstmt = conn.prepareStatement(sql);
                  pstmt.setString(1,tmp);
                  rs = pstmt.executeQuery();
                  if( rs.next() ){
                        String add1 = rs.getString("author");
                        authorTf.setText(add1);
                        String add2 = rs.getString("title");
                        titleTf.setText(add2);
                        String add3 = rs.getString("quantity");
                        quantityTf.setText(add3);
                        String add4 = rs.getString("bookid");
                        bidTf.setText(add4);
                        conn.close();
                  }
                  if( tmp != (String)"0"){
                        newBookBtn.setEnabled(false);
                        modBookBtn.setEnabled(true);
                        newTrBtn.setEnabled(true);
                  }else{
                        newBookBtn.setEnabled(true);
                        setbidTf("");
                        modBookBtn.setEnabled(false);
                        newTrBtn.setEnabled(false);
                        setauthorTf("");
                        settitleTf("");
                        setquantityTf("");
                  }
                  
                  if( getbidTf().getText().length() > 0 && getmidTf().getText().length() > 0 ){
                        newTrBtn.setEnabled(true);
                  }else{
                        newTrBtn.setEnabled(false);
                  }

            } catch (SQLException ex) {
                  ex.printStackTrace();
            }
      }//GEN-LAST:event_ComboBookPopupMenuWillBecomeInvisible

      private void ComboMemberPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboMemberPopupMenuWillBecomeInvisible
            // TODO add your handling code here:
            String tmp = ComboMember.getSelectedItem().toString();
            String sql = "select * from members where memberid = ?";
            try {
                  PreparedStatement pstmt = null;
                  ResultSet rs = null;
                  Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/library?user=root&password=");
                  pstmt = conn.prepareStatement(sql);
                  pstmt.setString(1,tmp);
                  rs = pstmt.executeQuery();
                  if( rs.next() ){
                        String add1 = rs.getString("name");
                        nameTf.setText(add1);
                        String add2 = rs.getString("phone");
                        phoneTf.setText(add2);
                        String add3 = rs.getString("email");
                        emailTf.setText(add3);
                        String add4 = rs.getString("memberid");
                        midTf.setText(add4);
                        String add5 = rs.getString("balance");
                        BalanceLbl.setText(add5);
                        conn.close();
                  }
                        
                    if( tmp != (String)"0"){
                        newMemberBtn.setEnabled(false);
                        modMemberBtn.setEnabled(true);
                        newTrBtn.setEnabled(true);
                  }else{
                        newMemberBtn.setEnabled(true);
                        setmidTf("");
                        newTrBtn.setEnabled(false);
                        modMemberBtn.setEnabled(false);
                        setnameTf("");
                        setphoneTf("");
                        setemailTf("");
                  }
                  
                  
                  if( getbidTf().getText().length() > 0 && getmidTf().getText().length() > 0 ){
                        newTrBtn.setEnabled(true);
                  }else{
                        newTrBtn.setEnabled(false);
                  }
                  
            } catch (SQLException ex) {
                  ex.printStackTrace();
            }
      }//GEN-LAST:event_ComboMemberPopupMenuWillBecomeInvisible

      private void ComboMemberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComboMemberKeyReleased
            // TODO add your handling code here:
      }//GEN-LAST:event_ComboMemberKeyReleased

      private void newTrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTrBtnActionPerformed
            // TODO add your handling code here:
            String tmp = ComboBook.getSelectedItem().toString();
            String sql = "select * from books where bookid = ?";
            String tmp2 = ComboMember.getSelectedItem().toString();
            String sql2 = "select * from members where memberid = ?";

            try {
                  PreparedStatement pstmt = null;
                  ResultSet rs = null;
                  Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/library?user=root&password=");
                  pstmt = conn.prepareStatement(sql);
                  pstmt.setString(1,tmp);
                  rs = pstmt.executeQuery();
                  if( rs.next() ){
                        String add = rs.getString("quantity");
                        quantityTf.setText(add);
                  }
                          
                  PreparedStatement pstmt2 = null;
                  ResultSet rs2 = null;
                  pstmt2 = conn.prepareStatement(sql2);
                  pstmt2.setString(1,tmp2);
                  rs2 = pstmt2.executeQuery();
                  if( rs2.next() ){
                        String add = rs2.getString("balance");
                        BalanceLbl.setText(add);
                  }
            
            }catch(SQLException ex){
                  ex.printStackTrace();
            }
      }//GEN-LAST:event_newTrBtnActionPerformed

      private void pfPINKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPINKeyReleased
            if( pfPIN.getText().length() > 0 ){
                  btnPIN.setEnabled(true);
            }else{
                  btnPIN.setEnabled(false);
            }
      }//GEN-LAST:event_pfPINKeyReleased

      private void newMemberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMemberBtnActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_newMemberBtnActionPerformed

      private void ComboMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMemberActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_ComboMemberActionPerformed
      
      
      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new MainFrame().setVisible(true);
                  }
            });
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalanceLbl;
    private javax.swing.JComboBox<String> ComboBook;
    private javax.swing.JComboBox<String> ComboMember;
    private javax.swing.JTable TblBook;
    private javax.swing.JTable TblMember;
    private javax.swing.JTable TblTran;
    private javax.swing.JTextField authorTf;
    private javax.swing.JTextField bidTf;
    private javax.swing.JButton btnPIN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBookBtn;
    private javax.swing.JButton cancelMemberBtn;
    private javax.swing.JButton cancelTrBtn;
    private javax.swing.JTextField emailTf;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField midTf;
    private javax.swing.JButton modBookBtn;
    private javax.swing.JButton modMemberBtn;
    private javax.swing.JTextField nameTf;
    private javax.swing.JButton newBookBtn;
    private javax.swing.JButton newMemberBtn;
    private javax.swing.JButton newTrBtn;
    private javax.swing.JPasswordField pfPIN;
    private javax.swing.JTextField phoneTf;
    private javax.swing.JTextField quantityTf;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JTable tblDebit;
    private javax.swing.JTextField titleTf;
    private javax.swing.JTextField trDirTf;
    private javax.swing.JLabel userLbl;
    private javax.swing.JLabel userTextLbl;
    private javax.swing.JLabel userTextLbl1;
    // End of variables declaration//GEN-END:variables

      
      public JTable getTblMember(){
            return TblMember;
      }
      
      public JTable getTblBook(){
            return TblBook;
      }

      public JTable getTblTran(){
            return TblTran;
      }

      public JTable getTblDebit(){
            return tblDebit;
      }

      public JTextField gettrDirTf(){
            return trDirTf;
      }
 
      public void settrDirTf(String text){
            trDirTf.setText(text);
      } 

      public JTextField getbidTf(){
            return bidTf;
      }
 
      public void setbidTf(String text){
            bidTf.setText(text);
      } 

      public JTextField getmidTf(){
            return midTf;
      }

      public void setmidTf(String text){
            midTf.setText(text);
      } 

      public String getComboBook(){
            return ComboBook.getSelectedItem().toString();
      }
 
      public void setComboBook(String text){
            ComboBook.setSelectedItem(text);
      } 

      public String getComboMember(){
            return ComboMember.getSelectedItem().toString();
      }
      
      public void setComboMember(String text){
            ComboMember.setSelectedItem(text);
      }
       
       public JLabel getstatusLbl(){
            return statusLbl;
      }

      public void setstatusLbl(String text){
            statusLbl.setText(text);
      }

       public JLabel getBalanceLbl(){
            return BalanceLbl;
      }

      public void setBalanceLbl(String text){
            BalanceLbl.setText(text);
      }

      public JLabel getuserLbl(){
            return userLbl;
      }

      public void setuserLbl(String text){
            userLbl.setText(text);
      }

      public JTextField getnameTf(){
            return nameTf;
      }

      public void setnameTf(String text){
            nameTf.setText(text);
      }
      
      public JTextField getphoneTf(){
            return phoneTf;
      }

      public void setphoneTf(String text){
            phoneTf.setText(text);
      }
      
      public JTextField getemailTf(){
            return emailTf;
      }

      public void setemailTf(String text){
            emailTf.setText(text);
      }
      
      public JButton getnewMemberBtn(){
            return newMemberBtn;
      }

      public void setnewMemberBtn(String text){
            newMemberBtn.setText(text);
      }

      public JButton getmodMemberBtn(){
            return modMemberBtn;
      }

      public void setmodMemberBtn(String text){
            modMemberBtn.setText(text);
      }

      public JButton getcancelMemberBtn(){
            return cancelMemberBtn;
      }

      public void setcancelMemberBtn(String text){
            cancelMemberBtn.setText(text);
      }

      public JButton getBtnPIN(){
            return btnPIN;
      }

      public void setBtnPIN(String text){
            btnPIN.setText(text);
      }

      public JButton getExitBtn(){
            return exitBtn;
      }

      public JTextField getauthorTf(){
            return authorTf;
      }

      public void setauthorTf(String text){
            authorTf.setText(text);
      }
      
      public JTextField gettitleTf(){
            return titleTf;
      }

      public void settitleTf(String text){
            titleTf.setText(text);
      }
      
      public JTextField getquantityTf(){
            return quantityTf;
      }

      public void setquantityTf(String text){
            quantityTf.setText(text);
      }
      
      public JButton getnewBookBtn(){
            return newBookBtn;
      }

      public void setnewBookBtn(String text){
            newBookBtn.setText(text);
      }

      public JButton getmodBookBtn(){
            return modBookBtn;
      }

      public void setmodBookBtn(String text){
            modBookBtn.setText(text);
      }

      public JButton getcancelBookBtn(){
            return cancelBookBtn;
      }

      public void setcancelBookBtn(String text){
            cancelBookBtn.setText(text);
      }

      public JButton getnewTrBtn(){
            return newTrBtn;
      }

      public void setnewTrBtn(String text){
            newTrBtn.setText(text);
      }

      public JButton getcancelTrBtn(){
            return cancelTrBtn;
      }

      public void setcancelTrBtn(String text){
            cancelTrBtn.setText(text);
      }
      
      public JPasswordField getPfPIN(){
            return pfPIN;
      }
      
      public void setPfPIN(String text){
            pfPIN.setText(text); 
      }      

      public void setMaxComboMember(){
            ComboMember.setSelectedItem(ComboMember.getItemAt(ComboMember.getItemCount()-1));
      }

      public void setMaxComboBook(){
            ComboBook.setSelectedItem(ComboBook.getItemAt(ComboBook.getItemCount()-1));
      }
      

      public void fillComboBook() {                                           
            try {
                  ComboBook.removeAllItems();
                  PreparedStatement pstmt = null;
                  ResultSet rs = null;
                  Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/library?user=root&password=");
                  String sql = "select * from books";
                  pstmt = conn.prepareStatement(sql);
                  rs = pstmt.executeQuery();
                  ComboBook.addItem("0");
                  while(rs.next()){
                        String lista = rs.getString("bookid"); 
                        ComboBook.addItem(lista);
                  }

                  rs.close();
                  pstmt.close();
                  conn.close();
                  
            } catch (SQLException ex) {
                  ex.printStackTrace();
            }
      }


      public void fillComboMember() {                                           
            try {
                  ComboMember.removeAllItems();
                  PreparedStatement pstmt = null;
                  ResultSet rs = null;
                  Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/library?user=root&password=");
                  String sql = "select * from members";
                  pstmt = conn.prepareStatement(sql);
                  rs = pstmt.executeQuery();
                  ComboMember.addItem("0");
                  while(rs.next()){
                        String lista = rs.getString("memberid"); 
                        ComboMember.addItem(lista);
                  }

                  rs.close();
                  pstmt.close();
                  conn.close();

            } catch (SQLException ex) {
                  ex.printStackTrace();
            }
      }

      public boolean chk_All_MData(){
            if(nameTf.getText().length()>0 && phoneTf.getText().length()>0 && emailTf.getText().length()>0 ){
                  return true;
            }else {
                  return false;
            }
      }

      public boolean chk_All_BData(){
            if(authorTf.getText().length()>0 && titleTf.getText().length()>0 && quantityTf.getText().length()>0 ){
                  return true;
            }else {
                  return false;
            }
      }

      public boolean chk_All_TData(){
            if(Integer.parseInt(quantityTf.getText()) > 0 ||  Integer.parseInt(quantityTf.getText()) == 0 && Integer.parseInt(trDirTf.getText()) > 0 ){
                  return true;
            }else {
                  return false;
            }
      }


}
